# Generated by Django 4.1.2 on 2023-05-06 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PN', 'Pasta-Napolitano'), ('PL', 'Prawn-Linguine'), ('RJ', 'RigatoniAll-Julio'), ('RD', 'Rigatonia-Dolcevita'), ('SB', 'SpagettiAlla-Bolognese'), ('SC', 'SpagettiAlla-Carbonara'), ('SM', 'Spagetti-Marina'), ('LZ', 'Lazagnea-Alforno')], max_length=2),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Adana', 'Adana'), ('Adıyaman', 'Adıyaman'), ('Afyonkarahisar', 'Afyonkarahisar'), ('Ankara', 'Ankara'), ('Antalya', 'Antalya'), ('Aydın', 'Aydın'), ('Balıkesir', 'Balıkesir'), ('Bursa', 'Bursa'), ('Çanakkale', 'Çanakkale'), ('Denizli', 'Denizli'), ('Edirne', 'Edirne'), ('Eskişehir', 'Eskişehir'), ('Gaziantep', 'Gaziantep'), ('Hatay', 'Hatay'), ('Isparta', 'Isparta'), ('İstanbul', 'İstanbul'), ('İzmir', 'İzmir'), ('Kahramanmaraş', 'Kahramanmaraş'), ('Kocaeli', 'Kocaeli'), ('Konya', 'Konya'), ('Kütahya', 'Kütahya'), ('Manisa', 'Manisa'), ('Mersin', 'Mersin'), ('Muğla', 'Muğla'), ('Sakarya', 'Sakarya'), ('Samsun', 'Samsun'), ('Sivas', 'Sivas'), ('Trabzon', 'Trabzon'), ('Uşak', 'Uşak'), ('Zonguldak', 'Zonguldak')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
